### ISSUE TITLE
Include Acid.nvim in clients list

### ISSUE THREAD

**Issue by hkupty** [nrepl/nrepl.org#4]
Hi,

First of all, thank you all very much for the effort and the nice work on nREPL.

I'm the writer and maintainer of [acid.nvim](https://github.com/clojure-vim/acid.nvim), a neovim plugin for providing asynchronous support to clojure through nREPL.

I think it can be added to the clients list on nREPL page.

Thanks in advance,
Henry J. Kupty

**Comment by cichli** [comment]
All done: https://nrepl.org/nrepl/usage/clients.html

Acid.nvim looks great – fantastic work!
